name: cv_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
#  sdk: '>=3.3.1 <4.0.0'
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.0
  intl:
  flutter_svg: ^2.0.7
  # ? Shared Preferences
  shared_preferences: ^2.2.2
  http: ^0.13.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  awesome_dialog: ^3.2.0
  shimmer:
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  firebase_auth: any
  firebase_core: any
  firebase_database: any
#  firebase_database: any
  firebase_storage: any
  sqflite: ^2.0.0
  path: ^1.8.0
  pdf: ^3.3.0
  printing: ^5.0.0
  flutter_pdfview: ^1.0.6
  bottom_bar_matu: ^1.3.0
  webview_flutter: ^4.7.0
  share_plus: ^8.0.2
  docx_template: ^0.4.0
#  pdftron_flutter: ^1.0.1-29
  path_provider: ^2.0.5
  url_launcher: ^6.1.14




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cv.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/logo.jpeg
    - assets/images/
    - assets/images/3.jpeg
    - assets/svg/
    - assets/cv/
    - assets/cv/cv1.svg
    - assets/svg/imgLang.svg
    - assets/svg/forgot_password2.svg




  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
          style: normal


    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Italic.ttf
          weight: 300
          style: normal

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
          style: normal


flutter_intl:
  enabled: true
  main_locale: ar